import { StyleSheet, Platform } from 'react-native';

const logoGreen = '#10B981';
const baseColor = '#F8FAFC';

export const getStyles = (theme, isDarkMode) => StyleSheet.create({
  container: { flex: 1, backgroundColor: theme?.background || '#F8FAFC' },
  headerArea: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: Platform.OS === 'ios' ? 60 : 40,
    paddingHorizontal: 24,
    marginBottom: 14,
  },
  headerTitleCenter: {
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: theme?.textPrimary || '#64748B'
  },
  scanBadgePill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginTop: 4,
  },
  normalBadgePill: {
    backgroundColor: isDarkMode ? 'rgba(16, 185, 129, 0.16)' : 'rgba(16, 185, 129, 0.10)',
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(16, 185, 129, 0.3)' : 'rgba(16, 185, 129, 0.2)',
  },
  warningBadgePill: {
    backgroundColor: isDarkMode ? 'rgba(239, 68, 68, 0.16)' : 'rgba(254, 242, 242, 1)',
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(239, 68, 68, 0.35)' : 'rgba(252, 165, 165, 0.8)',
  },
  premiumBadgePill: {
    backgroundColor: isDarkMode ? 'rgba(139, 92, 246, 0.16)' : 'rgba(245, 243, 255, 1)',
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(139, 92, 246, 0.35)' : 'rgba(221, 214, 254, 0.8)',
  },
  scanBadgeText: {
    fontSize: 11,
    fontWeight: '800',
  },
  normalBadgeText: {
    color: '#10B981',
  },
  warningBadgeText: {
    color: '#EF4444',
  },
  premiumBadgeText: {
    color: '#8B5CF6',
  },
  headerIconBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme?.surface || '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme?.border || '#E2E8F0',
    shadowOpacity: 0,
    elevation: 0,
  },
  cameraContainer: {
    flex: 1,
    marginHorizontal: 24,
    borderRadius: 32,
    overflow: 'hidden',
    backgroundColor: '#000',
    position: 'relative',
    shadowOpacity: 0,
    elevation: 0,
    marginBottom: 14,
  },
  camera: {
    width: '100%',
    height: '100%',
    zIndex: 1,
  },
  capturedOverlayImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    zIndex: 10,
  },
  viewfinderContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 20,
  },
  viewfinderBox: {
    width: 280,
    height: 280,
    position: 'relative',
    overflow: 'hidden',
  },
  corner: {
    position: 'absolute',
    width: 36,
    height: 36,
    borderColor: '#FFFFFF',
  },
  topLeft: { top: 0, left: 0, borderTopWidth: 3.5, borderLeftWidth: 3.5, borderTopLeftRadius: 14 },
  topRight: { top: 0, right: 0, borderTopWidth: 3.5, borderRightWidth: 3.5, borderTopRightRadius: 14 },
  bottomLeft: { bottom: 0, left: 0, borderBottomWidth: 3.5, borderLeftWidth: 3.5, borderBottomLeftRadius: 14 },
  bottomRight: { bottom: 0, right: 0, borderBottomWidth: 3.5, borderRightWidth: 3.5, borderBottomRightRadius: 14 },
  scanningLine: {
    position: 'absolute',
    top: 0,
    left: 4,
    right: 4,
    height: 2.5,
    backgroundColor: '#10B981',
    borderRadius: 2,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.8,
    shadowRadius: 6,
    elevation: 4,
  },
  visualTipsCard: {
    marginHorizontal: 24,
    marginBottom: 12,
    backgroundColor: theme?.surface || '#FFFFFF',
    borderRadius: 20,
    padding: 14,
    borderWidth: 1,
    borderColor: theme?.border || '#E2E8F0',
    shadowOpacity: 0,
    elevation: 0,
  },
  tipsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  tipsIconBg: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: isDarkMode ? 'rgba(245, 158, 11, 0.18)' : 'rgba(245, 158, 11, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  tipsCardTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: theme?.textPrimary || '#0F172A',
    flex: 1,
  },
  closeTipsBtn: {
    padding: 4,
  },
  tipsBulletPoint: {
    fontSize: 12,
    color: theme?.textSecondary || '#64748B',
    lineHeight: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  warningAlertBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: isDarkMode ? 'rgba(245, 158, 11, 0.12)' : 'rgba(254, 243, 199, 0.4)',
    borderRadius: 12,
    padding: 8,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(245, 158, 11, 0.25)' : 'rgba(253, 230, 138, 0.7)',
  },
  warningAlertText: {
    flex: 1,
    fontSize: 11,
    color: theme?.textSecondary || '#475569',
    lineHeight: 15,
    fontWeight: '600',
  },
  reopenTipsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: theme?.surface || '#FFFFFF',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: theme?.border || '#E2E8F0',
  },
  reopenTipsText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#10B981',
  },
  bottomControlsArea: {
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  instructionText: {
    color: theme?.textPrimary || '#64748B',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 14,
  },
  shutterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    position: 'relative',
    height: 76,
  },
  galleryButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: theme?.surface || '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme?.border || '#E2E8F0',
    shadowOpacity: 0,
    elevation: 0,
    position: 'absolute',
    left: '20%',
  },
  shutterOuter: {
    width: 76,
    height: 76,
    borderRadius: 38,
    borderWidth: 4,
    borderColor: '#10B981',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F1F5F9'
  },
  shutterInner: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#10B981',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  aiBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDarkMode ? 'rgba(16, 185, 129, 0.16)' : 'rgba(16, 185, 129, 0.10)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(16, 185, 129, 0.3)' : 'rgba(16, 185, 129, 0.2)',
  },
  aiBadgeText: {
    color: logoGreen,
    fontSize: 12,
    fontWeight: '700',
  },
  confidenceText: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '600',
  },
  floatingCloseBtn: {
    position: 'absolute',
    top: 40,
    left: 20,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  subTitleLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: theme?.textSecondary || '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 8,
    marginTop: 4,
  },
  gramInputCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: theme?.cardBg || (isDarkMode ? '#1E293B' : '#F1F5F9'),
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 12,
    borderWidth: 1.2,
    borderColor: theme?.border || (isDarkMode ? '#334155' : '#E2E8F0'),
  },
  stepperButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: theme?.surface || (isDarkMode ? '#334155' : '#FFFFFF'),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme?.border || '#E2E8F0',
  },
  gramInputWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gramTextInput: {
    fontSize: 22,
    fontWeight: '900',
    color: logoGreen,
    textAlign: 'center',
    paddingHorizontal: 4,
    paddingVertical: 2,
    minWidth: 60,
  },
  gramSuffixText: {
    fontSize: 14,
    fontWeight: '800',
    color: theme?.textSecondary || '#64748B',
    marginLeft: 4,
  },
  portionScaleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  scaleChip: {
    flex: 1,
    paddingVertical: 10,
    marginHorizontal: 3,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme?.cardBg || '#F1F5F9',
    borderWidth: 1,
    borderColor: theme?.border || '#E2E8F0',
  },
  scaleChipActive: {
    backgroundColor: isDarkMode ? 'rgba(16, 185, 129, 0.18)' : 'rgba(16, 185, 129, 0.12)',
    borderColor: logoGreen,
    borderWidth: 1.5,
  },
  scaleChipText: {
    fontSize: 12,
    fontWeight: '800',
    color: theme?.textSecondary || '#64748B',
  },
  scaleChipTextActive: {
    color: logoGreen,
    fontWeight: '900',
  },
  mealTypeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  mealTypeChip: {
    flex: 1,
    paddingVertical: 10,
    marginHorizontal: 3,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme?.border || '#E2E8F0',
  },
  mealTypeChipText: {
    fontSize: 12,
    fontWeight: '800',
  },
  foodName: {
    fontSize: 24,
    fontWeight: '800',
    color: theme?.textPrimary || '#0F172A',
    marginBottom: 12,
  },
  portionText: {
    fontSize: 14,
    fontWeight: '700',
    color: theme?.textSecondary || '#94A3B8',
    marginTop: -14,
    marginBottom: 20,
  },
  macroCardGrid: {
    flexDirection: 'row',
    backgroundColor: theme?.cardBg || '#F8FAFC',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme?.border || '#F1F5F9',
    paddingVertical: 16,
    marginBottom: 24,
  },
  macroCard: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  macroValue: {
    fontSize: 20,
    fontWeight: '800',
    color: theme?.textPrimary || '#0F172A',
    marginBottom: 4,
  },
  macroLabel: {
    fontSize: 12,
    color: theme?.textSecondary || '#94A3B8',
    fontWeight: '600',
  },
  logButton: {
    flexDirection: 'row',
    backgroundColor: logoGreen,
    height: 56,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  logButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  retakeButton: {
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
  },
  retakeButtonText: {
    color: theme?.textSecondary || '#94A3B8',
    fontSize: 16,
    fontWeight: '600',
  },
  permissionContainer: {
    flex: 1,
    backgroundColor: theme?.background || baseColor,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  permissionTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: theme?.textPrimary || '#0F172A',
    marginBottom: 12,
  },
  permissionText: {
    fontSize: 15,
    color: theme?.textSecondary || '#64748B',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 30,
  },
  permissionButton: {
    backgroundColor: logoGreen,
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 16,
  },
  permissionButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  closeButtonAbsolute: {
    position: 'absolute',
    top: 50,
    left: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme?.surface || '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme?.border || '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
});
