import { StyleSheet, Platform } from 'react-native';

const baseColor = '#F8FAFC';

export const getStyles = (theme, isDarkMode) => StyleSheet.create({
  fullscreenOverlay: { 
    flex: 1,
    backgroundColor: theme?.background || baseColor,
  },
  header: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 60 : 50,
    paddingBottom: 20,
    backgroundColor: theme?.surface || baseColor,
    borderBottomWidth: 1,
    borderBottomColor: theme?.border || '#E2E8F0',
    gap: 8,
  },
  backButton: { 
    width: 44, 
    height: 44, 
    borderRadius: 22, 
    backgroundColor: theme?.surface || baseColor, 
    alignItems: 'center', 
    justifyContent: 'center',
    borderWidth: 1.5, 
    borderColor: theme?.border || '#E2E8F0',
    shadowOpacity: 0,
    elevation: 0,
  },
  headerTitleGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  headerTitle: { 
    fontSize: 22, 
    fontWeight: '900', 
    color: theme?.textPrimary || '#0F172A', 
    letterSpacing: -0.5,
  },
  badge: {
    backgroundColor: '#EF4444',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    marginLeft: 8,
  },
  badgeText: {
    color: '#FFF',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 12,
    gap: 4,
  },
  markReadBtn: {
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
  },
  markReadText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#10B981',
  },
  clearAllBtn: {
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
  },
  clearAllText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#EF4444',
  },
  container: { flex: 1 },
  scrollContent: { 
    paddingHorizontal: 20, 
    paddingTop: 20, 
    paddingBottom: 60,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: theme?.textSecondary || '#94A3B8',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  subHeaderActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    width: '100%',
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  notificationCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme?.surface || baseColor,
    borderRadius: 18,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1, 
    borderColor: theme?.border || '#E2E8F0',
  },
  unreadCard: {
    backgroundColor: isDarkMode ? '#1E293B' : '#FFFFFF',
    borderColor: isDarkMode ? 'rgba(16, 185, 129, 0.4)' : 'rgba(16, 185, 129, 0.6)',
    borderWidth: 1.5,
  },
  iconBox: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  notifContent: { flex: 1 },
  notifHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  notifTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: theme?.textPrimary || '#64748B',
    flex: 1,
    marginRight: 8,
  },
  unreadText: {
    fontWeight: '900',
    color: theme?.textPrimary || '#0F172A',
  },
  notifTime: {
    fontSize: 11,
    color: theme?.textSecondary || '#94A3B8',
    fontWeight: '600',
  },
  notifMessage: {
    fontSize: 13,
    color: theme?.textSecondary || '#64748B',
    lineHeight: 18,
    fontWeight: '500',
  },
  rightActions: {
    alignItems: 'center',
    marginLeft: 8,
    gap: 6,
  },
  unreadDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#64748B',
  },
  dismissBtn: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: theme?.cardBg || '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dismissX: {
    fontSize: 10,
    color: theme?.textSecondary || '#94A3B8',
    fontWeight: '800',
    lineHeight: 14,
  },
  emptyState: {
    marginTop: 80,
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  emptyIconCircle: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: isDarkMode ? 'rgba(16, 185, 129, 0.16)' : 'rgba(16, 185, 129, 0.10)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    borderWidth: 2,
    borderColor: isDarkMode ? 'rgba(16, 185, 129, 0.3)' : 'rgba(16, 185, 129, 0.2)',
    shadowOpacity: 0,
    elevation: 0,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: theme?.textPrimary || '#0F172A',
    marginBottom: 12,
    letterSpacing: -0.3,
  },
  emptySubtitle: {
    fontSize: 14,
    color: theme?.textSecondary || '#94A3B8',
    textAlign: 'center',
    lineHeight: 22,
    fontWeight: '500',
  },
  footerInfo: {
    marginTop: 30,
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  footerText: {
    textAlign: 'center',
    marginTop: 12,
    fontSize: 12,
    color: theme?.textSecondary || '#94A3B8',
    lineHeight: 18,
    fontWeight: '500',
  },
});
